baseURL = 'https://jmeiss.me/'
languageCode = 'en-us'
title = 'Jeremy Meiss'
enableEmoji = true
theme = 'hugo-profile'

enableRobotsTXT = true

[markup]
    defaultMarkdownHandler = 'goldmark'
    [markup.goldmark]
        [markup.goldmark.renderer]
            unsafe = true
        [markup.goldmark.renderHooks]
            [markup.goldmark.renderHooks.image]
                useEmbedded = 'auto'
            [markup.goldmark.renderHooks.link]
                useEmbedded = 'auto'
    [markup.tableOfContents]
        startLevel = 2
        endLevel = 6
        ordered = false

[outputs]
home = [ "HTML", "RSS", "JSON" ]
page = [ "HTML", "RSS" ]

[pagination]
pagerSize = 9

[menus]
  [[menus.main]]
    identifier = "posts"
    name = "Posts"
    title = "Blog posts"
    url = "/posts/"
    weight = 1

[frontmatter]
date = ["publishDate", "date", ":default"]

