"use client";

import { useCallback, useEffect, useRef, useState } from "react";
import Link from "next/link";
import { cn } from "@/lib/cn";

interface PagefindResult {
  id: string;
  data: () => Promise<{
    url: string;
    excerpt: string;
    meta: { title?: string };
  }>;
}

interface PagefindAPI {
  init?: () => Promise<void>;
  options?: (opts: Record<string, unknown>) => Promise<void>;
  search: (query: string) => Promise<{ results: PagefindResult[] }>;
}

let pagefindInstance: PagefindAPI | null = null;
let pagefindLoadingError: Error | null = null;
let pagefindLoadingPromise: Promise<PagefindAPI> | null = null;

/**
 * Load Pagefind at runtime. Uses a string-form `import()` so neither webpack
 * nor turbopack tries to resolve the path at build time — Pagefind's index
 * (and `pagefind.js`) lives in `public/pagefind/` and is only generated by
 * the post-build pagefind step.
 */
async function loadPagefind(): Promise<PagefindAPI> {
  if (pagefindInstance) return pagefindInstance;
  if (pagefindLoadingError) throw pagefindLoadingError;
  if (pagefindLoadingPromise) return pagefindLoadingPromise;

  pagefindLoadingPromise = (async () => {
    try {
      const url = `${window.location.origin}/pagefind/pagefind.js`;
      const mod = (await (Function("u", "return import(u)") as (u: string) => Promise<unknown>)(
        url,
      )) as { default?: PagefindAPI; search?: PagefindAPI["search"] };
      const candidate = mod.search ? (mod as unknown as PagefindAPI) : mod.default;
      if (!candidate) throw new Error("Pagefind module has no API surface.");
      const api: PagefindAPI = candidate;
      if (api.init) await api.init();
      pagefindInstance = api;
      return api;
    } catch (err) {
      pagefindLoadingError = err instanceof Error ? err : new Error(String(err));
      throw pagefindLoadingError;
    }
  })();

  return pagefindLoadingPromise;
}

interface ResultRow {
  url: string;
  title: string;
  excerpt: string;
}

interface SearchModalProps {
  onClose: () => void;
}

/**
 * The search modal body — Pagefind loader, debounced search, results list.
 * Loaded lazily via `next/dynamic` from `SearchDialog` so this code only
 * ships once the user actually opens search (Cmd/Ctrl+K, "/", or click).
 */
export default function SearchModal({ onClose }: SearchModalProps) {
  const [query, setQuery] = useState("");
  const [results, setResults] = useState<ResultRow[]>([]);
  const [error, setError] = useState<string | null>(null);
  const [loading, setLoading] = useState(false);
  const inputRef = useRef<HTMLInputElement>(null);
  const dialogRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    inputRef.current?.focus();
    const prevOverflow = document.body.style.overflow;
    document.body.style.overflow = "hidden";
    return () => {
      document.body.style.overflow = prevOverflow;
    };
  }, []);

  const runSearch = useCallback(async (q: string) => {
    setError(null);
    if (!q.trim()) {
      setResults([]);
      return;
    }
    setLoading(true);
    try {
      const api = await loadPagefind();
      const { results: hits } = await api.search(q);
      const rows: ResultRow[] = await Promise.all(
        hits.slice(0, 20).map(async (hit) => {
          const data = await hit.data();
          return {
            url: data.url,
            title: data.meta.title ?? data.url,
            excerpt: data.excerpt,
          };
        }),
      );
      setResults(rows);
    } catch (err) {
      setError(err instanceof Error ? err.message : String(err));
      setResults([]);
    } finally {
      setLoading(false);
    }
  }, []);

  useEffect(() => {
    const id = setTimeout(() => {
      void runSearch(query);
    }, 120);
    return () => clearTimeout(id);
  }, [query, runSearch]);

  return (
    <div
      role="dialog"
      aria-modal="true"
      aria-label="Search posts"
      className="fixed inset-0 z-50 flex items-start justify-center bg-ink/60 p-4 sm:pt-20"
      onClick={(e) => {
        if (e.target === e.currentTarget) onClose();
      }}
      ref={dialogRef}
    >
      <div className="w-full max-w-2xl border border-ink bg-paper hard-shadow-ink">
        <div className="flex items-center gap-3 border-b border-ink px-4 py-3">
          <span aria-hidden className="font-mono text-sm text-muted">
            ⌕
          </span>
          <input
            ref={inputRef}
            type="search"
            value={query}
            onChange={(e) => setQuery(e.target.value)}
            placeholder="Search posts…"
            aria-label="Search posts"
            autoComplete="off"
            spellCheck={false}
            className="w-full bg-transparent font-body text-base text-ink outline-none placeholder:text-muted"
          />
          <button
            type="button"
            onClick={onClose}
            className="font-mono text-[10px] uppercase tracking-[0.14em] text-muted hover:text-ink"
          >
            Esc
          </button>
        </div>

        <div className="max-h-[60vh] overflow-y-auto">
          {error ? (
            <p className="px-4 py-6 text-sm text-warm">
              Search isn&apos;t available right now. (Pagefind index may be missing.)
            </p>
          ) : loading ? (
            <p className="px-4 py-6 text-sm text-muted">Searching…</p>
          ) : results.length === 0 && query ? (
            <p className="px-4 py-6 text-sm text-muted">
              No matches for <strong>{query}</strong>.
            </p>
          ) : results.length === 0 ? (
            <p className="px-4 py-6 text-sm text-muted">
              Type to search posts. <kbd>/</kbd> opens, <kbd>Esc</kbd> closes.
            </p>
          ) : (
            <ul>
              {results.map((r) => (
                <li key={r.url} className="border-b border-rule last:border-b-0">
                  <Link
                    href={r.url}
                    onClick={onClose}
                    className={cn(
                      "block px-4 py-3 transition-colors hover:bg-card focus:bg-card",
                    )}
                  >
                    <p className="font-display text-lg leading-tight text-ink">
                      {r.title}
                    </p>
                    <p
                      className="mt-1 line-clamp-2 text-sm text-ink-soft"
                      dangerouslySetInnerHTML={{ __html: r.excerpt }}
                    />
                  </Link>
                </li>
              ))}
            </ul>
          )}
        </div>
      </div>
    </div>
  );
}
