"use client";

import { useCallback, useEffect, useRef, useState } from "react";
import Link from "next/link";
import { cn } from "@/lib/cn";
import { isOffSiteHref, offSiteAnchorProps } from "@/lib/off-site-href-core";

interface PagefindResult {
  id: string;
  data: () => Promise<{
    url: string;
    excerpt: string;
    meta: { title?: string };
  }>;
}

interface PagefindAPI {
  init?: () => Promise<void>;
  options?: (opts: Record<string, unknown>) => Promise<void>;
  search: (query: string) => Promise<{ results: PagefindResult[] }>;
}

let pagefindInstance: PagefindAPI | null = null;
let pagefindLoadingError: Error | null = null;
let pagefindLoadingPromise: Promise<PagefindAPI> | null = null;

/**
 * Load Pagefind at runtime. Uses a string-form `import()` so neither webpack
 * nor turbopack tries to resolve the path at build time — Pagefind's index
 * (and `pagefind.js`) lives in `public/pagefind/` and is only generated by
 * the post-build pagefind step.
 */
async function loadPagefind(): Promise<PagefindAPI> {
  if (pagefindInstance) return pagefindInstance;
  if (pagefindLoadingError) throw pagefindLoadingError;
  if (pagefindLoadingPromise) return pagefindLoadingPromise;

  pagefindLoadingPromise = (async () => {
    try {
      const url = `${window.location.origin}/pagefind/pagefind.js`;
      const mod = (await (Function("u", "return import(u)") as (u: string) => Promise<unknown>)(
        url,
      )) as { default?: PagefindAPI; search?: PagefindAPI["search"] };
      const candidate = mod.search ? (mod as unknown as PagefindAPI) : mod.default;
      if (!candidate) throw new Error("Pagefind module has no API surface.");
      const api: PagefindAPI = candidate;
      if (api.init) await api.init();
      pagefindInstance = api;
      return api;
    } catch (err) {
      pagefindLoadingError = err instanceof Error ? err : new Error(String(err));
      throw pagefindLoadingError;
    }
  })();

  return pagefindLoadingPromise;
}

interface ResultRow {
  url: string;
  title: string;
  excerpt: string;
}

interface SearchModalProps {
  onClose: () => void;
}

const FOCUSABLE =
  'a[href], button:not([disabled]), input:not([disabled]), textarea:not([disabled]), select:not([disabled]), [tabindex]:not([tabindex="-1"])';

function getFocusableElements(container: HTMLElement): HTMLElement[] {
  return Array.from(container.querySelectorAll<HTMLElement>(FOCUSABLE)).filter(
    (el) => !el.hasAttribute("disabled") && el.getAttribute("aria-hidden") !== "true",
  );
}

/**
 * The search modal body — Pagefind loader, debounced search, results list.
 * Loaded lazily via `next/dynamic` from `SearchDialog` so this code only
 * ships once the user actually opens search (Cmd/Ctrl+K, "/", or click).
 */
export default function SearchModal({ onClose }: SearchModalProps) {
  const [query, setQuery] = useState("");
  const [results, setResults] = useState<ResultRow[]>([]);
  const [error, setError] = useState<string | null>(null);
  const [loading, setLoading] = useState(false);
  const [statusMessage, setStatusMessage] = useState("");
  const inputRef = useRef<HTMLInputElement>(null);
  const panelRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    inputRef.current?.focus();
    const prevOverflow = document.body.style.overflow;
    document.body.style.overflow = "hidden";
    return () => {
      document.body.style.overflow = prevOverflow;
    };
  }, []);

  useEffect(() => {
    const panel = panelRef.current;
    if (!panel) return;

    const onKeyDown = (e: KeyboardEvent) => {
      if (e.key === "Escape") {
        e.preventDefault();
        onClose();
        return;
      }
      if (e.key !== "Tab") return;

      const focusable = getFocusableElements(panel);
      if (focusable.length === 0) return;

      const first = focusable[0];
      const last = focusable[focusable.length - 1];

      if (e.shiftKey && document.activeElement === first) {
        e.preventDefault();
        last.focus();
      } else if (!e.shiftKey && document.activeElement === last) {
        e.preventDefault();
        first.focus();
      }
    };

    document.addEventListener("keydown", onKeyDown);
    return () => document.removeEventListener("keydown", onKeyDown);
  }, [onClose]);

  const runSearch = useCallback(async (q: string) => {
    setError(null);
    if (!q.trim()) {
      setResults([]);
      setStatusMessage("");
      return;
    }
    setLoading(true);
    setStatusMessage("Searching…");
    try {
      const api = await loadPagefind();
      const { results: hits } = await api.search(q);
      const rows: ResultRow[] = await Promise.all(
        hits.slice(0, 20).map(async (hit) => {
          const data = await hit.data();
          return {
            url: data.url,
            title: data.meta.title ?? data.url,
            excerpt: data.excerpt,
          };
        }),
      );
      setResults(rows);
      setStatusMessage(
        rows.length === 0
          ? `No matches for ${q}.`
          : `${rows.length} result${rows.length === 1 ? "" : "s"} for ${q}.`,
      );
    } catch (err) {
      setError(err instanceof Error ? err.message : String(err));
      setResults([]);
      setStatusMessage("Search is not available right now.");
    } finally {
      setLoading(false);
    }
  }, []);

  useEffect(() => {
    const id = setTimeout(() => {
      void runSearch(query);
    }, 120);
    return () => clearTimeout(id);
  }, [query, runSearch]);

  return (
    <div
      role="dialog"
      aria-modal="true"
      aria-label="Search posts"
      className="fixed inset-0 z-50 flex items-start justify-center p-4 sm:pt-20"
    >
      <button
        type="button"
        tabIndex={-1}
        aria-hidden="true"
        className="absolute inset-0 cursor-default bg-ink/60"
        onClick={onClose}
      />
      <div
        ref={panelRef}
        className="relative z-10 w-full max-w-2xl border border-ink bg-paper hard-shadow-ink"
      >
        <div className="flex items-center gap-3 border-b border-ink px-4 py-3">
          <span aria-hidden className="font-mono text-sm text-muted">
            ⌕
          </span>
          <input
            ref={inputRef}
            type="search"
            value={query}
            onChange={(e) => setQuery(e.target.value)}
            placeholder="Search posts…"
            aria-label="Search posts"
            aria-controls="search-results"
            autoComplete="off"
            spellCheck={false}
            className="w-full bg-transparent font-body text-base text-ink placeholder:text-muted"
          />
          <button
            type="button"
            onClick={onClose}
            aria-label="Close search"
            className="font-mono text-[10px] uppercase tracking-[0.14em] text-muted hover:text-ink"
          >
            <span aria-hidden>Esc</span>
          </button>
        </div>

        <div
          id="search-results"
          className="max-h-[60vh] overflow-y-auto"
          aria-live="polite"
          aria-busy={loading}
        >
          <p className="sr-only">{statusMessage}</p>
          {error ? (
            <p className="px-4 py-6 text-sm text-warm">
              Search isn&apos;t available right now. (Pagefind index may be missing.)
            </p>
          ) : loading ? (
            <p className="px-4 py-6 text-sm text-muted" aria-hidden>
              Searching…
            </p>
          ) : results.length === 0 && query ? (
            <p className="px-4 py-6 text-sm text-muted" aria-hidden>
              No matches for <strong>{query}</strong>.
            </p>
          ) : results.length === 0 ? (
            <p className="px-4 py-6 text-sm text-muted">
              Type to search posts. <kbd>/</kbd> opens, <kbd>Esc</kbd> closes.
            </p>
          ) : (
            <ul>
              {results.map((r) => {
                const origin = window.location.origin;
                return (
                  <li key={r.url} className="border-b border-rule last:border-b-0">
                    {isOffSiteHref(r.url, origin) ? (
                      <a
                        href={r.url}
                        onClick={onClose}
                        className={cn(
                          "block px-4 py-3 transition-colors hover:bg-card focus:bg-card",
                        )}
                        {...offSiteAnchorProps(r.url, origin)}
                      >
                        <p className="font-display text-lg leading-tight text-ink">
                          {r.title}
                        </p>
                        <p
                          className="mt-1 line-clamp-2 text-sm text-ink-soft"
                          dangerouslySetInnerHTML={{ __html: r.excerpt }}
                        />
                      </a>
                    ) : (
                      <Link
                        href={r.url}
                        onClick={onClose}
                        className={cn(
                          "block px-4 py-3 transition-colors hover:bg-card focus:bg-card",
                        )}
                      >
                        <p className="font-display text-lg leading-tight text-ink">
                          {r.title}
                        </p>
                        <p
                          className="mt-1 line-clamp-2 text-sm text-ink-soft"
                          dangerouslySetInnerHTML={{ __html: r.excerpt }}
                        />
                      </Link>
                    )}
                  </li>
                );
              })}
            </ul>
          )}
        </div>
      </div>
    </div>
  );
}
