import type { MetadataRoute } from "next";
import { siteConfig } from "@/content/site";

/**
 * Web app manifest. Generated by Next so it ships at /manifest.webmanifest
 * and is automatically referenced via the `manifest` field in the root
 * layout's Metadata. Keeps Lighthouse's installable-manifest, themed-omnibox,
 * splash-screen, and maskable-icon audits informed even though we are not
 * shipping a service worker (the site is content, not an app).
 */
export default function manifest(): MetadataRoute.Manifest {
  return {
    name: siteConfig.title,
    short_name: "jmeiss",
    description: siteConfig.description,
    start_url: "/",
    display: "minimal-ui",
    background_color: "#ffffff",
    theme_color: "#0b0d10",
    icons: [
      {
        src: "/icon-192.png",
        sizes: "192x192",
        type: "image/png",
        purpose: "any",
      },
      {
        src: "/icon-512.png",
        sizes: "512x512",
        type: "image/png",
        purpose: "any",
      },
      {
        src: "/icon-512.png",
        sizes: "512x512",
        type: "image/png",
        purpose: "maskable",
      },
    ],
  };
}
